# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=25)),
                ('legajo', models.IntegerField(blank=True, unique=True)),
                ('grado', models.CharField(choices=[('1', 'Bombero'), ('2', 'Cabo'), ('3', 'Cabo 1')], max_length=1)),
            ],
        ),
    ]
