# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roperia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RopaDeIncendio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcion_de_la_ropa', models.CharField(choices=[('1', 'Incendio'), ('2', 'Rescate'), ('3', 'Fajina'), ('4', 'Mameluco')], max_length=1)),
                ('inventario', models.IntegerField(unique=True)),
                ('prenda', models.CharField(choices=[('1', 'Casco'), ('2', 'Monja'), ('3', 'Guantes'), ('4', 'Saco')], max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='persona',
            name='legajo',
            field=models.IntegerField(unique=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='RopaDeIncendio',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='roperia.RopaDeIncendio'),
        ),
    ]
