# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roperia', '0002_auto_20170226_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='RopaDeIncendio',
        ),
        migrations.AddField(
            model_name='ropadeincendio',
            name='comodatario',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='roperia.Persona'),
        ),
    ]
